import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const html=readFileSync(resolve(root,"index.html"),"utf8"),app=readFileSync(resolve(root,"src/app.js"),"utf8"),styles=readFileSync(resolve(root,"styles.css"),"utf8"),manifest=JSON.parse(readFileSync(resolve(root,"manifest.webmanifest"),"utf8")),sw=readFileSync(resolve(root,"sw.js"),"utf8");
test("все ID-селекторы приложения существуют",()=>{const selectors=[...app.matchAll(/\$\("#([\w-]+)"\)/g)].map((m)=>m[1]);const missing=[...new Set(selectors)].filter((id)=>!html.includes(`id="${id}"`));assert.deepEqual(missing,[]);});
test("элементы управления имеют уникальные ID",()=>{const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map((m)=>m[1]);assert.equal(new Set(ids).size,ids.length);});
test("сенсорный интерфейс учитывает безопасные зоны",()=>{for(const marker of ["env(safe-area-inset-top)","env(safe-area-inset-right)","touch-action:none","orientation:portrait"])assert.ok(styles.includes(marker),marker);});
test("PWA работает без внешних ресурсов",()=>{assert.equal(manifest.display,"standalone");assert.equal(manifest.orientation,"landscape");for(const icon of manifest.icons)assert.ok(existsSync(resolve(root,icon.src)));for(const match of sw.matchAll(/"\.\/([^"?]+)"/g))assert.ok(existsSync(resolve(root,match[1])),match[1]);assert.equal(/https?:\/\//.test(`${html}\n${styles}\n${app}`),false);});
test("обязательные мобильные элементы присутствуют",()=>{for(const id of ["gameCanvas","steeringWheel","gasButton","brakeButton","handbrakeButton","cameraButton","engineButton","gearButton"])assert.ok(html.includes(`id="${id}"`));});
