import Phaser from 'phaser';
import './style.css';
import {RaidScene} from './scene';
import {Controls} from './input';
import {Sound} from './audio';
import {clock,nextWeapon,unlock,readScores,saveScore,readSettings,type Weapon} from './rules';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const screen=$('screen'),settings=readSettings(localStorage),sound=new Sound(settings),scene=new RaidScene();let chosen=0,noticeTimer=0,resumeMenu=false;
const controls=new Controls($('stick'),$('knob'),a=>{if(a==='pause')togglePause();else scene.action(a);});scene.controls=controls;scene.sfx=sound;
function display(html:string,cls=''){screen.innerHTML=`<section class="panel ${cls}">${html}</section>`;screen.hidden=false;$('controls').hidden=true;controls.clear();}
function bind(id:string,fn:()=>void){$(id).addEventListener('click',()=>{sound.unlock();fn();});}
function hideScreen(){screen.hidden=true;$('controls').hidden=false;$('hud').hidden=false;}
function menu(){scene.mode='menu';$('hud').hidden=true;display(`<div class="heading"><p class="eyebrow">РЯЗАНСКИЙ ПРОСПЕКТ</p><h1>ПОСЛЕДНИЙ<br>РЕЙД</h1><p class="sub">Два друга. Знакомый район.<br>И очень плохой вечер.</p></div><div class="pick"><button id="choose0" class="${chosen===0?'selected':''}" aria-pressed="${chosen===0}"><img src="./assets/kolya.webp" alt="Коля"><b>Коля</b><small>Быстрее и проворнее</small></button><button id="choose1" class="${chosen===1?'selected':''}" aria-pressed="${chosen===1}"><img src="./assets/valera.webp" alt="Валера"><b>Валера</b><small>Крепче и сильнее</small></button></div><button id="start" class="primary">В РЕЙД ↗</button><div class="row"><button id="scores" class="secondary">Рекорды</button><button id="settings" class="secondary">Настройки</button></div><p class="footnote">Карта: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · ODbL<br>Боссы являются вымышленными персонажами</p>`,'start-panel');for(let i=0;i<2;i++)bind('choose'+i,()=>{chosen=i;for(let j=0;j<2;j++){$('choose'+j).classList.toggle('selected',i===j);$('choose'+j).setAttribute('aria-pressed',String(i===j));}});bind('start',()=>{scene.reset(chosen,true);hideScreen();tutorial(true);});bind('scores',scores);bind('settings',()=>{resumeMenu=true;showSettings();});}
function tutorial(first=false){scene.mode='paused';display(`<p class="eyebrow">ВЫЖИВАЙТЕ ВМЕСТЕ</p><h2>Держитесь рядом</h2><p>Джойстик слева двигает героя. Обычные атаки автоматические. Спутник прикрывает вас.</p><p><b>✦</b> Усиленный удар · <b>➤</b> Рывок · <b>⇄</b> Смена героя<br>После каждых 10 убийств выбирайте улучшение.</p><p class="sub">ПК: WASD / стрелки, Space, Shift, Q / Tab.<br>G: граната после открытия. Escape: пауза.</p><button id="continue" class="primary">${first?'ПОЕХАЛИ':'ПРОДОЛЖИТЬ'}</button>`);bind('continue',()=>{scene.mode='playing';hideScreen();scene.hooks.notice('Рязанский проспект · держитесь вместе',2);});}
function togglePause(){if(scene.mode==='playing'){scene.mode='paused';pause();}else if(scene.mode==='paused'){scene.mode='playing';hideScreen();}}
function pause(){display(`<p class="eyebrow">ПЕРЕДЫШКА</p><h2>Район подождёт</h2><p>${clock(scene.run.seconds)} · ${scene.run.kills} убийств · уровень ${scene.run.level}</p><button id="resume" class="primary">ПРОДОЛЖИТЬ</button><div class="row"><button id="settings" class="secondary">Настройки</button><button id="help" class="secondary">Управление</button></div><div class="row"><button id="restart" class="secondary">Заново</button><button id="menu" class="secondary">В меню</button></div>`);bind('resume',()=>{scene.mode='playing';hideScreen();});bind('settings',()=>{resumeMenu=false;showSettings();});bind('help',()=>tutorial());bind('restart',()=>{scene.reset(chosen);hideScreen();});bind('menu',menu);}
function showSettings(){display(`<h2>Настройки</h2><div class="setting"><label for="sound">Звук</label><input id="sound" type="checkbox" ${settings.sound?'checked':''}></div><div class="setting"><label for="vibration">Вибрация</label><input id="vibration" type="checkbox" ${settings.vibration?'checked':''}></div><p class="sub">Вибрация доступна, если её поддерживает браузер. Качество эффектов подстраивается автоматически.</p><button id="back" class="primary">ГОТОВО</button>`);for(const key of ['sound','vibration'] as const)$(key).addEventListener('change',()=>{settings[key]=($<HTMLInputElement>(key)).checked;try{localStorage.setItem('last-raid-settings-v1',JSON.stringify(settings));}catch{scene.hooks.notice('Браузер не разрешил сохранить настройки');}});bind('back',()=>resumeMenu?menu():pause());}
function scores(){const list=readScores(localStorage);display(`<p class="eyebrow">ЛУЧШИЕ ЗАБЕГИ НА ЭТОМ УСТРОЙСТВЕ</p><h2>Таблица рейдов</h2>${list.length?`<table><thead><tr><th>№</th><th>Убийства</th><th>Время</th><th>Боссы</th></tr></thead><tbody>${list.map((s,i)=>`<tr><td>${i+1}</td><td>${s.kills}</td><td>${clock(s.seconds)}</td><td>${s.bosses}</td></tr>`).join('')}</tbody></table>`:'<p>Первый рекорд ещё впереди.</p>'}<button id="back" class="primary">В МЕНЮ</button>`);bind('back',menu);}
const descriptions:Record<Weapon,string>={'Дубинки':'Ближний бой','Усиленная бита':'Урон дубинок повышается с 22 до 30','Пистолет':'Автоматический огонь на дальней дистанции','Дробовик':'Пять дробин против плотной толпы','Гранаты':'5 гранат. Кнопка ✹ или G для броска','Коктейль':'Автоматические броски. Огонь остаётся на земле'};
function upgrades(){const w=nextWeapon(scene.run);const general=[{name:'Тяжёлая рука',desc:'Весь урон +20%',icon:'✦',fn:()=>scene.run.damage*=1.2},{name:'Второе дыхание',desc:'Здоровье +25 и лечение живых героев',icon:'✚',fn:()=>{for(const h of scene.heroes){h.max+=25;if(h.hp>0)h.hp=Math.min(h.max,h.hp+55);}}},{name:'Лёгкий шаг',desc:'Скорость передвижения +10%',icon:'➤',fn:()=>scene.run.speed=Math.min(1.7,scene.run.speed*1.1)},{name:'Широкий замах',desc:'Радиус атак и взрывов +12%',icon:'◎',fn:()=>scene.run.radius=Math.min(2,scene.run.radius*1.12)},{name:'Защитный жилет',desc:'Каждое попадание наносит на 2 меньше урона',icon:'⬡',fn:()=>scene.run.armor+=2},{name:'Быстрая перезарядка',desc:'Атаки и усиленный удар на 10% чаще',icon:'↻',fn:()=>scene.run.cooldown=Math.max(.35,scene.run.cooldown*.9)},{name:'Надёжное плечо',desc:'Урон оружия спутника +25%',icon:'⇄',fn:()=>scene.run.companion*=1.25}].filter(x=>!(x.name==='Лёгкий шаг'&&scene.run.speed>=1.7)&&!(x.name==='Широкий замах'&&scene.run.radius>=2)&&!(x.name==='Быстрая перезарядка'&&scene.run.cooldown<=.35));
 const offset=(scene.run.level*3)%general.length;const choices=w?[{name:w,desc:descriptions[w],icon:'✧',fn:()=>unlock(scene.run,w)},general[offset],general[(offset+1)%general.length]]:[general[offset],general[(offset+1)%general.length],general[(offset+2)%general.length]];
 display(`<p class="eyebrow">ОТРЯД СТАЛ СИЛЬНЕЕ</p><h2>Уровень ${scene.run.level-scene.run.pending+1}</h2><p class="sub">Выберите одно улучшение</p>${choices.map((c,i)=>`<button id="upgrade${i}" class="upgrade ${i===0&&w?'new':''}"><span class="icon">${c.icon}</span><span><strong>${i===0&&w?'НОВОЕ · ':''}${c.name}</strong><small>${c.desc}</small></span></button>`).join('')}`);
 choices.forEach((c,i)=>bind('upgrade'+i,()=>{c.fn();scene.run.pending--;if(scene.run.pending>0)upgrades();else{scene.mode='playing';hideScreen();scene.hooks.hud();sound.play('pickup');}}));}
function over(){const r=scene.run;if(!scene.deadSaved){scene.deadSaved=true;if(!saveScore(localStorage,r))scene.hooks.notice('Рекорд не сохранён: хранилище недоступно',4);}const best=readScores(localStorage)[0];display(`<p class="eyebrow">РЕЙД ЗАВЕРШЁН</p><h2>До следующего раза</h2><div class="statgrid"><div><b>${clock(r.seconds)}</b><small>Время выживания</small></div><div><b>${r.kills}</b><small>Убийства</small></div><div><b>${r.bossesDefeated}</b><small>Побеждено боссов</small></div><div><b>${r.level}</b><small>Уровень отряда</small></div></div><p>Лучший результат: <b>${best?.kills??r.kills}</b> убийств</p><button id="again" class="primary">ЕЩЁ РАЗ</button><div class="row"><button id="menu" class="secondary">В меню</button><button id="scores" class="secondary">Рекорды</button></div>`);bind('again',()=>{scene.reset(chosen);hideScreen();});bind('menu',menu);bind('scores',scores);}
function hud(){for(const h of scene.heroes){$('hp'+h.id).style.width=Math.max(0,h.hp/h.max*100)+'%';$('hptext'+h.id).textContent=`${Math.ceil(h.hp)} / ${h.max}`;$('hero'+h.id).classList.toggle('active',h.id===scene.active);$('hero'+h.id).style.opacity=h.hp<=0?'.4':'1';}$('level').textContent='УР. '+scene.run.level;$('kills').textContent=`${scene.run.kills%10} / 10 · ☠ ${scene.run.kills}`;$('xp').style.width=scene.run.kills%10*10+'%';$('timer').textContent=clock(scene.run.seconds);$('weapon').textContent=scene.run.weapons.slice(scene.run.weapons.length>1?1:0).join(' · ');$('combo').textContent=scene.combo>2?'СЕРИЯ ×'+scene.combo:'';$('grenade').hidden=!scene.run.weapons.includes('Гранаты');$('grenades').textContent=String(scene.run.grenades);$('bossbar').hidden=!scene.boss;if(scene.boss){$('bossname').textContent=scene.bossTitle;$('bosshp').style.width=Math.max(0,scene.boss.hp/scene.boss.max*100)+'%';}if(scene.heroes.length){$('heavy').style.setProperty('--cool',Math.max(0,scene.hero.heavyCD/(2.5*scene.run.cooldown)*100)+'%');$('dash').style.setProperty('--cool',Math.max(0,scene.hero.dashCD/2.4*100)+'%');}}
scene.hooks={ready:menu,hud,upgrade:upgrades,over,notice:(text,seconds=2)=>{clearTimeout(noticeTimer);$('notice').textContent=text;$('notice').classList.add('show');noticeTimer=window.setTimeout(()=>$('notice').classList.remove('show'),seconds*1000);}};
const game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:window.innerWidth,height:window.innerHeight,backgroundColor:'#24484b',antialias:true,powerPreference:'high-performance',scene:[scene],audio:{noAudio:true},scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},fps:{target:60,smoothStep:true},render:{roundPixels:true}});
document.addEventListener('visibilitychange',()=>{controls.clear();if(document.hidden&&scene.mode==='playing'){scene.mode='paused';pause();}});window.addEventListener('pagehide',()=>{controls.clear();if(scene.mode==='playing'){scene.mode='paused';pause();}});window.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('resize',()=>controls.clear());
if(import.meta.hot)import.meta.hot.dispose(()=>{controls.destroy();game.destroy(true);});

export {scene,controls};
