const frame=document.getElementById('frame') as HTMLIFrameElement,result=document.getElementById('result')!,size=document.getElementById('viewport') as HTMLSelectElement;
const get=()=>{const w=frame.contentWindow as Window&{raidQA:any};return {w,d:frame.contentDocument!,api:w.raidQA};};
const report=(s:string)=>{result.textContent=s;};
size.onchange=()=>{const [w,h]=size.value.split(',');frame.width=w;frame.height=h;};
frame.onload=()=>report('Игра загружена. Выберите проверку.');
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
document.getElementById('checks')!.onclick=async()=>{const lines:string[]=[];const check=(name:string,ok:boolean)=>{lines.push(`${ok?'PASS':'FAIL'} ${name}`);report(lines.join('\n'));};try{const {d,api}=get();if(!api)throw Error('Game not ready');const s=api.scene;const click=(id:string)=>{const el=d.getElementById(id);if(!el)throw Error('Missing '+id);el.click();};
 check('canvas loaded',!!d.querySelector('canvas'));click('choose1');check('Valera selected',d.getElementById('choose1')?.getAttribute('aria-pressed')==='true');click('settings');const snd=d.getElementById('sound') as HTMLInputElement;const before=snd.checked;snd.click();check('sound toggle',snd.checked!==before);snd.click();click('back');click('scores');check('scores page',d.body.textContent!.includes('Таблица рейдов'));click('back');click('start');click('continue');await delay(100);check('both heroes alive',s.heroes.every((h:any)=>h.hp>0));
 const buttons=[...d.querySelectorAll('button')].filter(b=>b.getClientRects().length);check('all game buttons at least 52px',buttons.every(b=>{const r=b.getBoundingClientRect();return r.width>=52&&r.height>=52;}));check('no horizontal overflow',d.documentElement.scrollWidth===d.documentElement.clientWidth);
 const stick=d.getElementById('stick')!,r=stick.getBoundingClientRect();const pointer=(el:HTMLElement,type:string,id:number,x:number,y:number)=>{el.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,pointerType:'touch',clientX:x,clientY:y}));};
 // Synthetic concurrent PointerEvents test event routing; this is not hardware multitouch.
 const oldCapture=stick.setPointerCapture;stick.setPointerCapture=()=>{};
 pointer(stick,'pointerdown',11,r.left+r.width/2+35,r.top+r.height/2);const moving=api.controls.x>.5;const old=s.active;pointer(d.getElementById('switch')!,'pointerdown',12,0,0);pointer(d.getElementById('heavy')!,'pointerdown',13,0,0);check('concurrent stick + switch + strike',moving&&api.controls.x>.5&&s.active!==old&&s.hero.heavyCD>0);pointer(stick,'pointercancel',11,0,0);check('cancel releases joystick',api.controls.x===0&&api.controls.pointer===null);stick.setPointerCapture=oldCapture;
 pointer(d.getElementById('dash')!,'pointerdown',14,0,0);check('dash activates',s.hero.dash>0);for(const weapon of api.WEAPONS.slice(1))api.unlock(s.run,weapon);s.hooks.hud();const count=s.run.grenades;pointer(d.getElementById('grenade')!,'pointerdown',15,0,0);check('grenade consumed and thrown',s.run.grenades===count-1&&s.throws.items.some((t:any)=>t.alive));
 await delay(1200);check('grenade detonates',s.throws.items.every((t:any)=>!t.alive));pointer(d.querySelector('[data-action="pause"]')! as HTMLElement,'pointerdown',16,0,0);check('pause shows menu',s.mode==='paused'&&!!d.getElementById('resume'));click('help');check('help opens',!!d.getElementById('continue'));click('continue');
 const first=s.enemies.items.find((e:any)=>e.alive);if(first){s.run.kills=9;s.kill(first);await delay(100);check('10th kill opens level 2',s.run.level===2&&s.mode==='upgrade');click('upgrade0');}
 for(const h of s.heroes){h.hp=0;h.invuln=0;}await delay(100);check('defeat screen',s.mode==='over'&&!!d.getElementById('again'));check('record saved',!!frame.contentWindow!.localStorage.getItem('last-raid-scores-v1'));click('again');check('restart clears state',s.run.kills===0&&s.run.level===1&&s.run.grenades===0&&s.run.bossesSpawned===0&&s.run.weapons.length===1);pointer(d.querySelector('[data-action="pause"]')! as HTMLElement,'pointerdown',17,0,0);click('menu');check('return to menu',!!d.getElementById('start'));report(lines.join('\n'));}catch(e){report(lines.join('\n')+'\nERROR '+String(e));}};
document.getElementById('stress')!.onclick=async()=>{const {d,api}=get();if(!api)return;const s=api.scene;d.getElementById('start')?.click();d.getElementById('continue')?.click();for(const w of api.WEAPONS)api.unlock(s.run,w);s.run.level=20;s.run.damage=2;let frames=0,total=0,min=Infinity,maxEnemies=0;const start=performance.now(),samples:number[]=[];let last=start;const step=()=>{const now=performance.now(),delta=now-last;last=now;if(delta>0&&frames>10){samples.push(delta);total+=delta;min=Math.min(min,1000/delta);}frames++;for(const h of s.heroes){h.hp=h.max;h.invuln=1;}if(s.mode==='upgrade')d.getElementById('upgrade0')?.click();if(s.mode==='playing'){while(s.enemies.items.filter((e:any)=>e.alive).length<170){if(!s.spawnEnemy())break;}s.hero.heavyCD=0;s.action('heavy');const t=(now-start)/1000;api.controls.x=Math.cos(t*.2)*.8;api.controls.y=Math.sin(t*.2)*.8;maxEnemies=Math.max(maxEnemies,s.enemies.items.filter((e:any)=>e.alive).length);}if(now-start<180000){report(`Нагрузка: ${Math.round((now-start)/1000)} / 180 с; враги ${maxEnemies}; средний FPS ${(samples.length/(total/1000)).toFixed(1)}`);requestAnimationFrame(step);}else{api.controls.clear();samples.sort((a,b)=>a-b);report(JSON.stringify({test:'180s stress',viewport:size.value,frames,meanFPS:samples.length/(total/1000),p95FrameMs:samples[Math.floor(samples.length*.95)],minFPS:min,maxEnemies,kills:s.run.kills,quality:s.quality,enemyPool:s.enemies.items.length,bulletPool:s.bullets.items.length,effectPool:s.effects.items.length,loadedChunks:s.world.chunks.size},null,2));}};requestAnimationFrame(step);};
