import Phaser from 'phaser';
import {World,type MapData} from './world';
import {createArt} from './art';
import {Pool,Spatial,newRun,addKill,nextBoss,useGrenade,type Point,type Run} from './rules';
import type {Controls} from './input';
import type {Sound} from './audio';
export type Mode='loading'|'menu'|'playing'|'upgrade'|'paused'|'over';
type Hero=Point&{id:number;hp:number;max:number;image:Phaser.GameObjects.Image;facing:number;attack:number;gun:number;shotgun:number;fire:number;invuln:number;dash:number;dashCD:number;heavyCD:number;walk:number;};
type Enemy=Point&{alive:boolean;hp:number;max:number;kind:number;elite:boolean;speed:number;r:number;image:Phaser.GameObjects.Image;hit:number;attack:number;kx:number;ky:number;boss:boolean;cycle:number;phase:number;phaseTime:number;aimX:number;aimY:number;};
type Bullet=Point&{alive:boolean;vx:number;vy:number;damage:number;life:number;hostile:boolean;r:number;image:Phaser.GameObjects.Image;};
type Effect=Point&{alive:boolean;kind:string;life:number;max:number;r:number;color:number;angle:number;};
type Hazard=Point&{alive:boolean;kind:string;time:number;duration:number;r:number;damage:number;fired:boolean;};
type Pickup=Point&{alive:boolean;kind:number;life:number;};
type Throw=Point&{alive:boolean;sx:number;sy:number;tx:number;ty:number;t:number;fire:boolean;};
type Crate=Point&{alive:boolean;hp:number;};
export interface Hooks {ready():void;hud():void;upgrade():void;over():void;notice(text:string,seconds?:number):void;}
const colors=[0x9bbf7a,0xc3cf68,0x8cbfab,0xb9a381,0xb884b6,0x8aa6b8,0xdf7254,0xbb88e5,0xd8bc64,0x70d4bf];
export class RaidScene extends Phaser.Scene {
 world!:World;heroes:Hero[]=[];active=0;run:Run=newRun();mode:Mode='loading';controls!:Controls;sfx!:Sound;hooks!:Hooks;
 enemies!:Pool<Enemy>;bullets!:Pool<Bullet>;effects!:Pool<Effect>;hazards!:Pool<Hazard>;pickups!:Pool<Pickup>;throws!:Pool<Throw>;crates:Crate[]=[];spatial=new Spatial<Enemy>(100);
 graphics!:Phaser.GameObjects.Graphics;labels:{text:Phaser.GameObjects.Text;life:number;x:number;y:number}[]=[];
 spawnTime=0;flowTime=0;hudTime=0;sectorTime=0;combo=0;comboUntil=0;buffUntil=0;boss:Enemy|undefined;bossTitle='';quality=2;fps=60;qualityTime=0;darkUntil=0;deadSaved=false;
 constructor(){super('Raid');}
 preload(){this.load.image('heroes','./assets/heroes.webp');this.load.json('map','./map.json');this.load.on('loaderror',()=>{const p=document.querySelector('#screen .panel');if(p)p.innerHTML='<h2>Не удалось загрузить игру</h2><p>Проверьте соединение и обновите страницу.</p><button class="primary" onclick="location.reload()">Повторить загрузку</button>';});}
 create(){createArt(this);this.world=new World(this,this.cache.json.get('map') as MapData);this.graphics=this.add.graphics().setDepth(100000);this.enemies=new Pool(180,()=>({alive:false,x:0,y:0,hp:0,max:0,kind:0,elite:false,speed:0,r:15,image:this.add.image(0,0,'enemies',0).setOrigin(.5,.75).setVisible(false),hit:0,attack:0,kx:0,ky:0,boss:false,cycle:0,phase:0,phaseTime:0,aimX:0,aimY:0}));
 this.bullets=new Pool(200,()=>({alive:false,x:0,y:0,vx:0,vy:0,damage:0,life:0,hostile:false,r:3,image:this.add.image(0,0,'dot').setVisible(false)}));
 this.effects=new Pool(180,()=>({alive:false,x:0,y:0,kind:'',life:0,max:0,r:0,color:0,angle:0}));this.hazards=new Pool(50,()=>({alive:false,x:0,y:0,kind:'',time:0,duration:0,r:0,damage:0,fired:false}));this.pickups=new Pool(100,()=>({alive:false,x:0,y:0,kind:0,life:0}));this.throws=new Pool(24,()=>({alive:false,x:0,y:0,sx:0,sy:0,tx:0,ty:0,t:0,fire:false}));
 for(let i=0;i<30;i++)this.labels.push({text:this.add.text(0,0,'',{fontFamily:'system-ui',fontSize:'15px',fontStyle:'bold',color:'#ffe6a3',stroke:'#183339',strokeThickness:3}).setDepth(100010).setVisible(false),life:0,x:0,y:0});
 for(let id=0;id<2;id++)this.heroes.push({id,x:0,y:0,hp:1,max:1,image:this.add.image(0,0,'heroes',id*3+1).setDisplaySize(78,78).setOrigin(.5,.91),facing:Math.PI/2,attack:0,gun:0,shotgun:0,fire:0,invuln:0,dash:0,dashCD:0,heavyCD:0,walk:0});
 this.cameras.main.setBounds(0,0,this.world.data.width,this.world.data.height);this.cameras.main.setBackgroundColor('#527467');this.reset(0,false);this.mode='menu';this.hooks.ready();}
 get hero(){return this.heroes[this.active];}
 reset(id=0,play=true){this.run=newRun();this.active=id;this.combo=0;this.comboUntil=0;this.buffUntil=0;this.darkUntil=0;this.boss=undefined;this.bossTitle='';this.deadSaved=false;this.spawnTime=.25;this.flowTime=0;this.hudTime=0;this.sectorTime=0;this.qualityTime=0;
 for(const p of [this.enemies,this.bullets,this.effects,this.hazards,this.pickups,this.throws])p.clear();for(const e of this.enemies.items)e.image.setVisible(false);for(const b of this.bullets.items)b.image.setVisible(false);for(const l of this.labels){l.life=0;l.text.setVisible(false);}this.spatial.clear();this.crates=[];
 const start=this.world.free(this.world.data.metro.x+30,this.world.data.metro.y+40);for(const h of this.heroes){const p=this.world.free(start.x+(h.id?45:0),start.y);Object.assign(h,p,{max:h.id?165:120,hp:h.id?165:120,attack:0,gun:0,shotgun:0,fire:0,invuln:1.2,dash:0,dashCD:0,heavyCD:0,walk:0});h.image.setVisible(true).setAlpha(1).clearTint();}
 for(let i=0;i<100;i++){const a=i*2.39996,r=160+Math.sqrt(i)*240;const p=this.world.free(start.x+Math.cos(a)*r,start.y+Math.sin(a)*r);if(!this.world.blocked(p.x,p.y,20))this.crates.push({...p,alive:true,hp:40});}this.world.lastTarget=-1;this.world.buildFlow(this.hero);this.controls?.clear();this.mode=play?'playing':'menu';this.cameras.main.centerOn(this.hero.x,this.hero.y);this.hooks.hud();}
 action(a:string){if(this.mode!=='playing')return;this.sfx.unlock();const h=this.hero;if(a==='switch'){const next=1-this.active;if(this.heroes[next].hp>0){this.active=next;this.world.lastTarget=-1;this.fx(h.x,h.y,'ring',40,0xa8e4cb,.3);this.sfx.play('pickup');this.hooks.hud();}return;}if(a==='dash'&&h.dashCD<=0){h.dash=.2;h.invuln=.35;h.dashCD=2.4;this.sfx.play('dash');return;}if(a==='heavy'&&h.heavyCD<=0){h.heavyCD=2.5*this.run.cooldown;this.melee(h,true);this.sfx.buzz(18);return;}if(a==='grenade'&&this.throws.items.some(p=>!p.alive)&&useGrenade(this.run)){this.throwAt(h,false);this.hooks.hud();}}
 update(_time:number,delta:number){if(!this.world)return;const dt=Math.min(delta/1000,.04);this.fps=this.fps*.97+Math.min(120,1000/Math.max(delta,1))*.03;this.qualityTime+=dt;if(this.qualityTime>4){if(this.fps<45)this.quality=Math.max(0,this.quality-1);else if(this.fps>56)this.quality=Math.min(2,this.quality+1);this.qualityTime=0;}
 const cam=this.cameras.main;const desiredX=this.hero.x-cam.width/2,desiredY=this.hero.y-cam.height*.51;cam.scrollX=Phaser.Math.Linear(cam.scrollX,desiredX,Math.min(1,dt*9));cam.scrollY=Phaser.Math.Linear(cam.scrollY,desiredY,Math.min(1,dt*9));
 this.sectorTime-=dt;if(this.sectorTime<=0){this.world.update(new Phaser.Geom.Rectangle(cam.scrollX,cam.scrollY,cam.width,cam.height));this.sectorTime=.25;}
 if(this.mode==='playing'){this.run.seconds+=dt;this.flowTime-=dt;if(this.flowTime<=0){this.world.buildFlow(this.hero);this.flowTime=.3;}this.spatial.clear();for(const e of this.enemies.items)if(e.alive)this.spatial.add(e);
 this.updateHeroes(dt);this.updateEnemies(dt);this.updateBullets(dt);this.updateHazards(dt);this.updateThrows(dt);this.updatePickups(dt);this.spawnTime-=dt;if(this.spawnTime<=0){this.spawnWave();this.spawnTime=Math.max(.24,1.0-this.run.level*.035);}if(!this.boss&&this.run.bossesQueued>0)this.spawnBoss();if(this.comboUntil<this.run.seconds)this.combo=0;
 if(this.heroes.every(h=>h.hp<=0)){this.mode='over';this.controls.clear();this.hooks.over();}else if(this.run.pending>0){this.mode='upgrade';this.controls.clear();this.sfx.play('level');this.hooks.upgrade();}
 this.hudTime-=dt;if(this.hudTime<=0){this.hooks.hud();this.hudTime=.1;}}
 this.render(dt);}
 updateHeroes(dt:number){for(const h of this.heroes){if(h.hp<=0){h.image.setVisible(false);continue;}for(const key of ['attack','gun','shotgun','fire','invuln','dashCD','heavyCD'] as const)h[key]-=dt;let v={x:0,y:0};if(h.id===this.active)v=this.controls.vector();else {const d=Phaser.Math.Distance.Between(h.x,h.y,this.hero.x,this.hero.y);if(d>62)v=this.world.direction(h,this.hero);}
 const speed=(h.id?145:171)*this.run.speed*(h.id===this.active?1:1.2);if(h.dash>0){h.dash-=dt;v={x:Math.cos(h.facing)*3.4,y:Math.sin(h.facing)*3.4};this.fx(h.x,h.y,'spark',8,h.id?0xf8b573:0x7de1ce,.16);}
 if(Math.hypot(v.x,v.y)>.08){h.facing=Math.atan2(v.y,v.x);this.world.move(h,v.x*speed*dt,v.y*speed*dt);h.walk+=dt*13;}else h.walk=0;
 if(h.attack<=0&&this.nearest(h,82*this.run.radius))this.melee(h,false);
 if(this.run.weapons.includes('Пистолет')&&h.gun<=0){const e=this.nearest(h,380);if(e){this.shoot(h,e,h.id===this.active?1:this.run.companion);h.gun=.72*this.run.cooldown;}}
 if(this.run.weapons.includes('Дробовик')&&h.shotgun<=0){const e=this.nearest(h,230);if(e){const a=Math.atan2(e.y-h.y,e.x-h.x);for(let i=-2;i<=2;i++)this.bullet(h,a+i*.12,460,15*this.run.damage*(h.id===this.active?1:this.run.companion),.48,false,3);h.shotgun=1.8*this.run.cooldown;this.sfx.play('shot');}}
 if(this.run.weapons.includes('Коктейль')&&h.fire<=0&&this.nearest(h,290)){this.throwAt(h,true);h.fire=5*this.run.cooldown;}
 h.image.setFrame(h.id*3+(Math.sin(h.facing)<-.25?2:1)).setFlipX(Math.cos(h.facing)<-.2).setPosition(h.x,h.y+Math.sin(h.walk)*2).setAngle(Math.sin(h.walk)*3).setDepth(h.y+100).setAlpha(h.invuln>0?.65+.35*Math.sin(this.run.seconds*35):1);
 }if(this.hero.hp<=0&&this.heroes[1-this.active].hp>0){this.active=1-this.active;this.hooks.notice('Второй герой продолжает бой');}}
 nearest(p:Point,r:number){let best:Enemy|undefined,dist=r*r;for(const e of this.spatial.near(p.x,p.y,r))if(e.alive){const d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<dist&&this.world.lineClear(p,e)){dist=d;best=e;}}return best;}
 melee(h:Hero,heavy:boolean){const target=this.nearest(h,120*this.run.radius);const a=target?Math.atan2(target.y-h.y,target.x-h.x):h.facing;const radius=(heavy?123:78)*this.run.radius;const bat=this.run.weapons.includes('Усиленная бита');const damage=(heavy?48:bat?30:22)*this.run.damage*(h.id===this.active?1:this.run.companion)*(this.buffUntil>this.run.seconds?1.55:1);h.attack=(h.id?.69:.52)*this.run.cooldown;this.fx(h.x,h.y,'slash',radius,heavy?0xffd28a:0xd9f2b3,.24,a);let hit=false;
 for(const e of this.spatial.near(h.x,h.y,radius+25))if(e.alive&&this.world.lineClear(h,e)){const ea=Math.atan2(e.y-h.y,e.x-h.x);if(Math.abs(Phaser.Math.Angle.Wrap(ea-a))<(heavy?1.7:1.2)){const crit=Math.random()<.12;this.hitEnemy(e,damage*(crit?1.8:1),h,(h.id?160:110)*(heavy?1.6:1),crit);hit=true;}}
 for(const c of this.crates)if(c.alive&&Math.hypot(c.x-h.x,c.y-h.y)<radius&&this.world.lineClear(h,c)){c.hp-=damage;if(c.hp<=0){c.alive=false;this.drop(c.x,c.y,Math.random()<.4?1:Math.random()<.5?2:3);this.fx(c.x,c.y,'burst',28,0xe8bb73,.3);}}
 if(hit){this.sfx.play('hit');this.cameras.main.shake(heavy?75:35,heavy?.002:.0009);this.sfx.buzz(8);}}
 shoot(h:Hero,e:Enemy,mul:number){this.bullet(h,Math.atan2(e.y-h.y,e.x-h.x),570,25*this.run.damage*mul,.7,false,3);this.sfx.play('shot');this.fx(h.x,h.y-12,'spark',12,0xffeabc,.12);}
 bullet(p:Point,a:number,speed:number,damage:number,life:number,hostile:boolean,r:number){const b=this.bullets.take();if(!b)return;Object.assign(b,{x:p.x,y:p.y-5,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,damage,life,hostile,r});b.image.setPosition(b.x,b.y).setTint(hostile?0xd9a1e4:0xffe8a0).setDisplaySize(r*2,r*2).setVisible(true).setDepth(50000);}
 hitEnemy(e:Enemy,damage:number,from:Point,knock=80,crit=false){if(!e.alive)return;const actual=damage*(e.kind===5?.65:1);e.hp-=actual;e.hit=.11;const d=Math.hypot(e.x-from.x,e.y-from.y)||1;e.kx+=(e.x-from.x)/d*knock*(e.boss?.1:1);e.ky+=(e.y-from.y)/d*knock*(e.boss?.1:1);this.damageText(e.x,e.y-44,`${crit?'✦ ':''}${Math.round(actual)}`,crit?'#ffbd6c':'#fff0b7');if(e.hp<=0)this.kill(e);}
 kill(e:Enemy){e.alive=false;e.image.setVisible(false);addKill(this.run);this.combo++;this.comboUntil=this.run.seconds+3;this.fx(e.x,e.y-12,'burst',e.boss?80:24,colors[e.kind],.35);if(e.boss){this.run.bossesDefeated++;this.boss=undefined;this.bossTitle='';this.drop(e.x,e.y,1);this.drop(e.x+24,e.y,2);this.drop(e.x-24,e.y,3);this.run.grenades+=this.run.weapons.includes('Гранаты')?3:0;this.hooks.notice('Босс побеждён! Припасы ваши');this.sfx.play('level');}else {const roll=Math.random();this.drop(e.x,e.y,roll<.09?1:roll<.12?2:roll<.145?3:0);}}
 hurt(h:Hero,damage:number){if(h.hp<=0||h.invuln>0)return;h.hp=Math.max(0,h.hp-Math.max(1,damage-this.run.armor));h.invuln=.65;this.fx(h.x,h.y,'ring',30,0xfa806c,.25);this.sfx.buzz(20);if(h.id===this.active)this.cameras.main.shake(80,.003);}
 spawnWave(){const count=1+Math.floor(Math.min(3,this.run.level/5));for(let i=0;i<count;i++)this.spawnEnemy();}
 spawnPoint(){const cam=this.cameras.main;for(let i=0;i<30;i++){const a=Math.random()*Math.PI*2;const r=Math.max(cam.width,cam.height)*.64+80;const p=this.world.free(this.hero.x+Math.cos(a)*r,this.hero.y+Math.sin(a)*r);if(p.x>cam.scrollX-65&&p.x<cam.scrollX+cam.width+65&&p.y>cam.scrollY-80&&p.y<cam.scrollY+cam.height+80)continue;const cell=Math.floor(p.y/32)*this.world.cols+Math.floor(p.x/32);if(!this.world.blocked(p.x,p.y,20)&&this.world.flow[cell]>=0)return p;}return null;}
 spawnEnemy(kind?:number,bossInfo?:{kind:number;cycle:number;name:string}){const p=this.spawnPoint();if(!p)return;const e=this.enemies.take();if(!e)return;const k=bossInfo?6+bossInfo.kind:kind??Math.floor(Math.random()*Math.min(6,1+Math.floor((this.run.level-1)/1.4)));const elite=!bossInfo&&this.run.level>=7&&Math.random()<.12;const cycle=bossInfo?.cycle??Math.floor(this.run.bossesDefeated/4);const mul=1+Math.max(0,this.run.level-1)*.045+cycle*.22;const hp=(bossInfo?750+bossInfo.kind*160:[38,29,22,135,52,95][k])*mul*(elite?2.1:1);Object.assign(e,p,{hp,max:hp,kind:k,elite,speed:(bossInfo?58:[48,96,77,36,45,43][k])*Math.min(1.65,1+this.run.level*.013)*(elite?1.16:1),r:bossInfo?28:k===3?22:k===2?10:15,hit:0,attack:1.3,kx:0,ky:0,boss:!!bossInfo,cycle,phase:0,phaseTime:2,aimX:0,aimY:0});e.image.setTexture('enemies',k).setDisplaySize(bossInfo?104:k===3?68:k===2?38:52,bossInfo?208:k===3?136:k===2?61:104).setVisible(true).setAlpha(1).clearTint();if(elite)e.image.setTint(0xffdf8e);if(bossInfo){this.boss=e;this.bossTitle=bossInfo.name+(cycle?' · '+(cycle+1):'');this.hooks.notice(bossInfo.name,3);this.sfx.play('boss');}return e;}
 spawnBoss(){// Reserve a slot for bosses even at the population cap; no kill credit for recycling.
 if(!this.enemies.items.some(e=>!e.alive)){const far=this.enemies.items.find(e=>!e.boss&&Math.hypot(e.x-this.hero.x,e.y-this.hero.y)>450);if(far){far.alive=false;far.image.setVisible(false);}}
 const next=nextBoss(this.run);if(next&&!this.spawnEnemy(undefined,next)){this.run.bossesQueued++;this.run.bossesSpawned--;}}
 updateEnemies(dt:number){for(const e of this.enemies.items){if(!e.alive)continue;e.hit-=dt;e.attack-=dt;const target=this.heroes.filter(h=>h.hp>0).sort((a,b)=>Math.hypot(e.x-a.x,e.y-a.y)-Math.hypot(e.x-b.x,e.y-b.y))[0];if(!target)continue;let d=Math.hypot(target.x-e.x,target.y-e.y);if(d>1900&&!e.boss){e.alive=false;e.image.setVisible(false);continue;}
 let v=this.world.direction(e,target);let movement=1;if(e.boss)movement=this.bossAI(e,target,dt);else if(e.kind===4&&d<310&&d>120&&this.world.lineClear(e,target)){movement=.1;if(e.attack<=0){const a=Math.atan2(target.y-e.y,target.x-e.x);this.hazard(target.x,target.y,28,'spit',.65,0,9);this.bullet(e,a,155,10,2.5,true,7);e.attack=2.3;}}
 if(d<e.r+15){if(e.attack<=0){this.hurt(target,(e.boss?23:e.kind===3?17:9)*(1+this.run.level*.035));e.attack=.8;}movement=0;}
 if(e.phase===2&&e.kind===6){v={x:e.aimX,y:e.aimY};movement=6;}
 const separation={x:0,y:0};for(const other of this.spatial.near(e.x,e.y,35)){if(other===e||!other.alive)continue;const ox=e.x-other.x,oy=e.y-other.y,len=Math.hypot(ox,oy);if(len>0&&len<e.r+other.r){separation.x+=ox/len*16;separation.y+=oy/len*16;}}
 this.world.move(e,(v.x*e.speed*movement+e.kx+separation.x)*dt,(v.y*e.speed*movement+e.ky+separation.y)*dt,e.r*.65);e.kx*=Math.exp(-dt*8);e.ky*=Math.exp(-dt*8);e.image.setPosition(e.x,e.y+Math.sin(this.run.seconds*7+e.x)*1.4).setDepth(e.y+90).setFlipX(target.x<e.x).setAngle(Math.sin(this.run.seconds*6+e.y)*2);if(e.hit>0)e.image.setTintFill(0xffefc3);else if(e.elite)e.image.setTint(0xffdd92);else e.image.clearTint();}}
 bossAI(e:Enemy,h:Hero,dt:number){e.phaseTime-=dt;const kind=e.kind-6;const a=Math.atan2(h.y-e.y,h.x-e.x);if(kind===0){if(e.phase===0&&e.phaseTime<=0){e.phase=1;e.phaseTime=1.0;e.aimX=Math.cos(a);e.aimY=Math.sin(a);this.hazard(e.x+e.aimX*150,e.y+e.aimY*150,60,'warn',1,0,0);}else if(e.phase===1&&e.phaseTime<=0){e.phase=2;e.phaseTime=.8;this.sfx.play('dash');}else if(e.phase===2){if(Math.hypot(e.x-h.x,e.y-h.y)<55)this.hurt(h,27);if(e.phaseTime<=0){e.phase=3;e.phaseTime=2;this.hazard(e.x,e.y,110,'blast',.9,0,27);}}else if(e.phase===3&&e.phaseTime<=0){e.phase=0;e.phaseTime=2;}return e.phase===1?0:1;}
 if(kind===1&&e.phaseTime<=0){if(e.phase%2===0){this.fx(e.x,e.y,'ring',90,0xcda2ee,.7);for(let i=-3-e.cycle;i<=3+e.cycle;i++)this.bullet(e,a+i*.18,145,15,3.8,true,7);}else{for(let i=0;i<5+Math.min(5,e.cycle);i++)this.spawnEnemy(i%3);}e.phase++;e.phaseTime=2.8;}
 if(kind===2){if(e.phase%2===0&&e.phaseTime<=0){this.hazard(e.x,e.y,140,'spin',1.1,1.7,22);e.phase++;e.phaseTime=3.2;}else if(e.phase%2===1&&e.phaseTime<=0){for(let i=0;i<3;i++)this.hazard(h.x+Math.cos(a+i*2)*65,h.y+Math.sin(a+i*2)*65,48,'blast',.95+i*.2,0,22);e.phase++;e.phaseTime=2.8;}}
 if(kind===3&&e.phaseTime<=0){if(e.phase%2===0){const p=this.world.free(h.x+Math.cos(a+2)*190,h.y+Math.sin(a+2)*190);this.fx(e.x,e.y,'ring',70,0x96e8d0,.6);e.x=p.x;e.y=p.y;this.fx(e.x,e.y,'ring',70,0x96e8d0,.6);this.darkUntil=this.run.seconds+2.5;}else for(let i=0;i<4;i++)this.hazard(h.x+Math.cos(i*1.57)*85,h.y+Math.sin(i*1.57)*85,62,'curse',1.2,2.2,16);e.phase++;e.phaseTime=3;}
 return .85;}
 updateBullets(dt:number){for(const b of this.bullets.items){if(!b.alive)continue;b.life-=dt;const steps=Math.max(1,Math.ceil(Math.hypot(b.vx,b.vy)*dt/12));for(let i=0;i<steps&&b.alive;i++){b.x+=b.vx*dt/steps;b.y+=b.vy*dt/steps;if(this.world.blocked(b.x,b.y,2)){b.alive=false;break;}if(b.hostile){for(const h of this.heroes)if(h.hp>0&&Math.hypot(b.x-h.x,b.y-h.y)<14+b.r){this.hurt(h,b.damage);b.alive=false;break;}}else for(const e of this.spatial.near(b.x,b.y,38))if(e.alive&&Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){this.hitEnemy(e,b.damage,{x:b.x-b.vx*.1,y:b.y-b.vy*.1},45);b.alive=false;break;}}
 if(b.life<=0)b.alive=false;b.image.setVisible(b.alive).setPosition(b.x,b.y);}}
 hazard(x:number,y:number,r:number,kind:string,warn:number,duration:number,damage:number){const z=this.hazards.take();if(z)Object.assign(z,{x,y,r,kind,time:-warn,duration,damage,fired:false});}
 updateHazards(dt:number){for(const z of this.hazards.items){if(!z.alive)continue;z.time+=dt;if(z.time>=0&&!z.fired){z.fired=true;if(z.kind==='blast'||z.kind==='spit'){this.fx(z.x,z.y,'burst',z.r,0xf69a79,.4);this.sfx.play('boom');for(const h of this.heroes)if(Math.hypot(h.x-z.x,h.y-z.y)<z.r)this.hurt(h,z.damage);}}
 if(z.time>=0&&z.time<z.duration){if(z.kind==='fire'&&Math.floor(z.time*4)!==Math.floor((z.time-dt)*4)){for(const e of this.spatial.near(z.x,z.y,z.r))if(e.alive)this.hitEnemy(e,z.damage*.25,z,0);}else for(const h of this.heroes)if(Math.hypot(h.x-z.x,h.y-z.y)<z.r)this.hurt(h,z.damage);}
 if(z.time>=z.duration)z.alive=false;}}
 throwAt(h:Hero,fire:boolean){const t=this.throws.take();if(!t)return;const e=this.nearest(h,360),aim=e??{x:h.x+Math.cos(h.facing)*220,y:h.y+Math.sin(h.facing)*220};Object.assign(t,{x:h.x,y:h.y,sx:h.x,sy:h.y,tx:aim.x,ty:aim.y,t:0,fire});this.sfx.play('dash');}
 updateThrows(dt:number){for(const t of this.throws.items){if(!t.alive)continue;t.t+=dt;const v=Math.min(1,t.t/.55);t.x=Phaser.Math.Linear(t.sx,t.tx,v);t.y=Phaser.Math.Linear(t.sy,t.ty,v);if(t.t>1){t.alive=false;const r=(t.fire?95:150)*this.run.radius;this.fx(t.tx,t.ty,'burst',r,t.fire?0xfbae57:0xffe6a3,.55);this.sfx.play('boom');this.cameras.main.shake(140,.004);for(const e of this.spatial.near(t.tx,t.ty,r))if(e.alive)this.hitEnemy(e,(t.fire?40:150)*this.run.damage,t,250);if(t.fire)this.hazard(t.tx,t.ty,r,'fire',0,4,17*this.run.damage);}}}
 drop(x:number,y:number,kind:number){const p=this.pickups.take();if(p)Object.assign(p,{x,y,kind,life:kind?45:15});}
 updatePickups(dt:number){for(const p of this.pickups.items){if(!p.alive)continue;p.life-=dt;if(p.life<=0){p.alive=false;continue;}for(const h of this.heroes)if(h.hp>0){const dx=h.x-p.x,dy=h.y-p.y,d=Math.hypot(dx,dy);if(d<100&&d>20){p.x+=dx/d*220*dt;p.y+=dy/d*220*dt;}if(d<24){p.alive=false;if(p.kind===1){h.hp=Math.min(h.max,h.hp+38);this.damageText(h.x,h.y-50,'+38','#a4efb1');}else if(p.kind===2){if(this.run.weapons.includes('Гранаты'))this.run.grenades+=2;else h.hp=Math.min(h.max,h.hp+15);}else if(p.kind===3){this.buffUntil=this.run.seconds+8;this.hooks.notice('Ярость · урон +55%',1.3);}else {h.heavyCD=Math.max(0,h.heavyCD-.08);this.fx(p.x,p.y,'spark',8,0xa0e4be,.15);}if(p.kind)this.sfx.play('pickup');break;}}}}
 fx(x:number,y:number,kind:string,r:number,color:number,life:number,angle=0){if(kind==='spark'&&this.quality===0)return;const e=this.effects.take();if(e)Object.assign(e,{x,y,kind,r,color,life,max:life,angle});}
 damageText(x:number,y:number,value:string,color:string){const l=this.labels.find(l=>l.life<=0);if(!l)return;l.life=.55;l.x=x;l.y=y;l.text.setText(value).setColor(color).setPosition(x,y).setVisible(true);}
 render(dt:number){const g=this.graphics;g.clear();const cam=this.cameras.main,visible=(p:Point,r=100)=>p.x>cam.scrollX-r&&p.x<cam.scrollX+cam.width+r&&p.y>cam.scrollY-r&&p.y<cam.scrollY+cam.height+r;
 for(const c of this.crates)if(c.alive&&visible(c)){g.fillStyle(0x223f3b,.4);g.fillRect(c.x-13,c.y-8,29,28);g.fillStyle(0xb58d58);g.fillRoundedRect(c.x-14,c.y-17,28,28,3);g.lineStyle(3,0x614d39);g.strokeRect(c.x-14,c.y-17,28,28);g.lineBetween(c.x-11,c.y-14,c.x+11,c.y+8);g.lineBetween(c.x+11,c.y-14,c.x-11,c.y+8);}
 for(const p of this.pickups.items)if(p.alive&&visible(p)){const bob=Math.sin(this.run.seconds*5+p.x)*2;if(p.kind===0){g.fillStyle(0xabe1ab,.9);g.fillPoints([{x:p.x,y:p.y-5+bob},{x:p.x+4,y:p.y+bob},{x:p.x,y:p.y+5+bob},{x:p.x-4,y:p.y+bob}],true);}else {g.fillStyle(0x173c3b,.5);g.fillEllipse(p.x,p.y+8,22,9);g.fillStyle(p.kind===1?0xe3edbf:p.kind===2?0xb6bc75:0xf6c268);g.fillRoundedRect(p.x-10,p.y-10+bob,20,20,4);g.fillStyle(p.kind===1?0xd96657:0x41594b);if(p.kind===1){g.fillRect(p.x-2,p.y-6+bob,4,12);g.fillRect(p.x-6,p.y-2+bob,12,4);}else if(p.kind===2)g.fillCircle(p.x,p.y+bob,6);else g.fillTriangle(p.x+2,p.y-8+bob,p.x-6,p.y+2+bob,p.x+5,p.y+bob);}}
 for(const z of this.hazards.items)if(z.alive&&visible(z,z.r)){const warning=z.time<0;const color=z.kind==='fire'?0xec984c:z.kind==='curse'?0xb493dd:0xf88a7b;g.fillStyle(color,warning?.1:.25);g.fillCircle(z.x,z.y,z.r);g.lineStyle(warning?3:2,color,.8);g.strokeCircle(z.x,z.y,z.r*(warning?.85+.12*Math.sin(this.run.seconds*12):1));if(warning){g.lineBetween(z.x-8,z.y,z.x+8,z.y);g.lineBetween(z.x,z.y-8,z.x,z.y+8);}if(z.kind==='spin'&&!warning){const a=this.run.seconds*10;g.lineStyle(8,0xfbd487,.8);g.lineBetween(z.x+Math.cos(a)*z.r,z.y+Math.sin(a)*z.r,z.x-Math.cos(a)*z.r,z.y-Math.sin(a)*z.r);}}
 for(const t of this.throws.items)if(t.alive){g.lineStyle(2,0xffe4a1,.8);g.strokeCircle(t.tx,t.ty,20);g.lineBetween(t.tx-8,t.ty,t.tx+8,t.ty);const arc=-Math.sin(Math.min(1,t.t/.55)*Math.PI)*75;g.fillStyle(t.fire?0xfac369:0x2c453c);g.fillCircle(t.x,t.y+arc,7);g.lineStyle(2,0xe4eac0);g.strokeCircle(t.x,t.y+arc,7);}
 for(const e of this.effects.items)if(e.alive){if(this.mode==='playing')e.life-=dt;if(e.life<=0){e.alive=false;continue;}const p=1-e.life/e.max;g.lineStyle(e.kind==='slash'?9:3,e.color,(1-p)*.85);if(e.kind==='slash'){g.beginPath();g.arc(e.x,e.y,e.r*.78,e.angle-1.2+p*.45,e.angle+.7+p*.8);g.strokePath();}else if(e.kind==='ring')g.strokeCircle(e.x,e.y,e.r*(.3+p*.7));else if(e.kind==='burst'){g.fillStyle(e.color,(1-p)*.23);g.fillCircle(e.x,e.y,e.r*p);g.strokeCircle(e.x,e.y,e.r*p);for(let n=0;n<(this.quality===0?3:8);n++){const a=n*.785+e.angle;g.fillStyle(e.color,1-p);g.fillCircle(e.x+Math.cos(a)*e.r*p,e.y+Math.sin(a)*e.r*p,5*(1-p));}}else{g.fillStyle(e.color,1-p);g.fillCircle(e.x,e.y,e.r*(1-p));}}
 for(const e of this.enemies.items)if(e.alive){e.image.setVisible(visible(e));if(e.hp<e.max&&visible(e)){g.fillStyle(0x153b3b,.8);g.fillRect(e.x-17,e.y-65,34,4);g.fillStyle(e.boss?0xf59588:0xb8d987);g.fillRect(e.x-17,e.y-65,34*e.hp/e.max,4);}if(e.elite&&visible(e)){g.lineStyle(2,0xf4d97c,.7);g.strokeEllipse(e.x,e.y,35,15);}}
 for(const h of this.heroes)if(h.hp>0){g.lineStyle(h.id===this.active?3:1,h.id?0xf3bc77:0x94e4d0,h.id===this.active?.9:.5);g.strokeEllipse(h.x,h.y+1,36,16);if(this.buffUntil>this.run.seconds){g.lineStyle(2,0xf2c969,.65);g.strokeCircle(h.x,h.y-18,33);}}
 for(const l of this.labels)if(l.life>0){if(this.mode==='playing'){l.life-=dt;l.y-=dt*33;}l.text.setPosition(l.x,l.y).setAlpha(Math.min(1,l.life*3));if(l.life<=0)l.text.setVisible(false);}
 if(this.quality>0){for(let i=0;i<7;i++){const x=cam.scrollX+((i*97+this.run.seconds*13)%cam.width),y=cam.scrollY+((i*137+this.run.seconds*18)%cam.height);g.fillStyle(0xe3d494,.28);g.fillEllipse(x,y,4,2);}for(let i=0;i<3;i++){const x=cam.scrollX+((i*239+this.run.seconds*27)%(cam.width+100))-50,y=cam.scrollY+100+i*64;g.lineStyle(1,0x223e42,.4);g.lineBetween(x-4,y-2,x,y);g.lineBetween(x,y,x+4,y-2);}}
 if(this.darkUntil>this.run.seconds){g.fillStyle(0x132438,.6);g.fillRect(cam.scrollX,cam.scrollY,cam.width,cam.height*.28);g.fillRect(cam.scrollX,cam.scrollY+cam.height*.72,cam.width,cam.height*.28);}
 }
}
