import Phaser from 'phaser';
import type {Point} from './rules';
export type Feature = {id:number;kind:string;name:string;points:number[][];minX:number;minY:number;maxX:number;maxY:number};
export type MapData = {width:number;height:number;features:Feature[];metro:Point;university:Point;source:string;};
export type Prop = Point & {kind:number;r:number};
const CELL=32,CHUNK=512;
function inside(x:number,y:number,pts:number[][]){let c=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const [a,b]=pts[i],[u,v]=pts[j];if((b>y)!==(v>y)&&x<(u-a)*(y-b)/(v-b)+a)c=!c;}return c;}
function rand(n:number){const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);}
export class World {
 cols:number;rows:number;solid:Uint8Array;flow:Int32Array;queue:Int32Array;chunks=new Map<string,Phaser.GameObjects.Image>();props:Prop[]=[];lastTarget=-1;
 constructor(public scene:Phaser.Scene,public data:MapData){this.cols=Math.ceil(data.width/CELL);this.rows=Math.ceil(data.height/CELL);this.solid=new Uint8Array(this.cols*this.rows);this.flow=new Int32Array(this.solid.length).fill(-1);this.queue=new Int32Array(this.solid.length);
 for(const f of data.features)if(f.kind==='building')for(let y=Math.max(0,Math.floor(f.minY/CELL));y<=Math.min(this.rows-1,Math.ceil(f.maxY/CELL));y++)for(let x=Math.max(0,Math.floor(f.minX/CELL));x<=Math.min(this.cols-1,Math.ceil(f.maxX/CELL));x++)if(inside(x*CELL+16,y*CELL+16,f.points))this.solid[y*this.cols+x]=1;
 for(let i=0;i<1900;i++){const x=70+rand(i*3)*(data.width-140),y=70+rand(i*3+1)*(data.height-140);if(!this.blocked(x,y,26)&&Math.hypot(x-data.metro.x,y-data.metro.y)>160){const kind=i%9;this.props.push({x,y,kind,r:kind===0?20:kind===1?11:0});if(kind===0)this.mark(x,y,20);}}
 }
 mark(x:number,y:number,r:number){for(let j=Math.floor((y-r)/CELL);j<=Math.floor((y+r)/CELL);j++)for(let i=Math.floor((x-r)/CELL);i<=Math.floor((x+r)/CELL);i++)if(i>=0&&j>=0&&i<this.cols&&j<this.rows)this.solid[j*this.cols+i]=1;}
 blocked(x:number,y:number,r=12){if(x<40||y<40||x>this.data.width-40||y>this.data.height-40)return true;for(const [dx,dy] of [[0,0],[r,0],[-r,0],[0,r],[0,-r]]){const i=Math.floor((y+dy)/CELL)*this.cols+Math.floor((x+dx)/CELL);if(this.solid[i])return true;}return false;}
 free(x:number,y:number){if(!this.blocked(x,y,20))return{x,y};for(let radius=32;radius<500;radius+=32)for(let a=0;a<Math.PI*2;a+=.4){const p={x:x+Math.cos(a)*radius,y:y+Math.sin(a)*radius};if(!this.blocked(p.x,p.y,20))return p;}return this.data.metro;}
 move(p:Point,dx:number,dy:number,r=12){let moved=false;if(!this.blocked(p.x+dx,p.y,r)){p.x+=dx;moved=true;}if(!this.blocked(p.x,p.y+dy,r)){p.y+=dy;moved=true;}return moved;}
 buildFlow(target:Point){const tx=Math.floor(target.x/CELL),ty=Math.floor(target.y/CELL),start=ty*this.cols+tx;if(start===this.lastTarget)return;this.lastTarget=start;this.flow.fill(-1);let head=0,tail=0;this.queue[tail++]=start;this.flow[start]=0;while(head<tail){const i=this.queue[head++],x=i%this.cols,y=Math.floor(i/this.cols);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,n=ny*this.cols+nx;if(nx<1||ny<1||nx>=this.cols-1||ny>=this.rows-1||this.solid[n]||this.flow[n]>=0)continue;this.flow[n]=this.flow[i]+1;this.queue[tail++]=n;}}}
 direction(p:Point,target:Point){const dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy)||1;if(this.lineClear(p,target))return{x:dx/d,y:dy/d};const x=Math.floor(p.x/CELL),y=Math.floor(p.y/CELL);let best=this.flow[y*this.cols+x],bx=x,by=y;for(const [ax,ay] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const nx=x+ax,ny=y+ay,n=ny*this.cols+nx;if(nx<0||ny<0||nx>=this.cols||ny>=this.rows)continue;if(ax&&ay&&(this.solid[y*this.cols+nx]||this.solid[ny*this.cols+x]))continue;if(this.flow[n]>=0&&(best<0||this.flow[n]<best)){best=this.flow[n];bx=nx;by=ny;}}if(bx===x&&by===y)return{x:0,y:0};const vx=bx*CELL+16-p.x,vy=by*CELL+16-p.y,len=Math.hypot(vx,vy)||1;return{x:vx/len,y:vy/len};}
 lineClear(a:Point,b:Point){const d=Math.hypot(a.x-b.x,a.y-b.y);for(let t=0;t<=d;t+=24){const u=d?t/d:0;if(this.blocked(a.x+(b.x-a.x)*u,a.y+(b.y-a.y)*u,8))return false;}return true;}
 update(view:Phaser.Geom.Rectangle){const needed=new Set<string>();for(let cy=Math.max(0,Math.floor(view.y/CHUNK)-1);cy<=Math.min(Math.ceil(this.data.height/CHUNK),Math.floor(view.bottom/CHUNK)+1);cy++)for(let cx=Math.max(0,Math.floor(view.x/CHUNK)-1);cx<=Math.min(Math.ceil(this.data.width/CHUNK),Math.floor(view.right/CHUNK)+1);cx++){const key=`sector-${cx}-${cy}`;needed.add(key);if(!this.chunks.has(key))this.makeChunk(cx,cy,key);}
 for(const [key,img] of this.chunks)if(!needed.has(key)){img.destroy();this.scene.textures.remove(key);this.chunks.delete(key);}}
 makeChunk(cx:number,cy:number,key:string){const ox=cx*CHUNK,oy=cy*CHUNK;const tex=this.scene.textures.createCanvas(key,CHUNK,CHUNK)!;const c=tex.context;c.fillStyle='#527467';c.fillRect(0,0,CHUNK,CHUNK);c.translate(-ox,-oy);c.lineJoin='round';c.lineCap='round';for(let i=0;i<60;i++){c.fillStyle=i%2?'#587b6b':'#4d6c60';c.fillRect(ox+rand(i+cx*4)*CHUNK,oy+rand(i*7+cy*13)*CHUNK,2,4);}
 const list=this.data.features.filter(f=>f.maxX>=ox-100&&f.minX<ox+CHUNK+100&&f.maxY>=oy-100&&f.minY<oy+CHUNK+100);
 const path=(f:Feature,dy=0)=>{c.beginPath();f.points.forEach(([x,y],i)=>i?c.lineTo(x,y+dy):c.moveTo(x,y+dy));};
 for(const f of list)if(f.kind!=='building'&&f.kind!=='metro'){const big=['primary','secondary','trunk'].includes(f.kind),foot=['footway','path','steps','pedestrian','cycleway'].includes(f.kind);const w=big?58:foot?13:26;path(f);c.strokeStyle=foot?'#a9ada1':'#a5ada8';c.lineWidth=w+14;c.stroke();path(f);c.strokeStyle=foot?'#9dada0':'#53616a';c.lineWidth=w;c.stroke();if(big){c.setLineDash([22,24]);c.strokeStyle='#bcc4b4';c.lineWidth=2;path(f);c.stroke();c.setLineDash([]);} }
 for(const f of list)if(f.kind==='building'){path(f,15);c.closePath();c.fillStyle='#203e3b88';c.fill();path(f,7);c.closePath();c.fillStyle='#52616a';c.fill();path(f);c.closePath();c.fillStyle=rand(f.id)>.5?'#92a7a4':'#a6b4a6';c.fill();c.lineWidth=4;c.strokeStyle='#314a4b';c.stroke();c.save();c.clip();c.strokeStyle='#b4c3b5';c.lineWidth=2;for(let y=f.minY+12;y<f.maxY;y+=24){c.beginPath();c.moveTo(f.minX+8,y);c.lineTo(f.maxX-8,y);c.stroke();}const bx=(f.minX+f.maxX)/2,by=(f.minY+f.maxY)/2;c.fillStyle='#667e7d';c.fillRect(bx-11,by-8,22,16);c.strokeStyle='#c0cfc0';c.strokeRect(bx-11,by-8,22,16);c.restore();}
 for(const p of this.props)if(p.x>ox-45&&p.x<ox+CHUNK+45&&p.y>oy-45&&p.y<oy+CHUNK+45){const{x,y,kind}=p;if(kind===0){c.save();c.translate(x,y);c.rotate(rand(x)*Math.PI);c.fillStyle='#263f3e66';c.fillRect(-15,-25,33,55);c.fillStyle=['#cc9363','#729fad','#ba6455'][Math.floor(x)%3];c.strokeStyle='#2b4145';c.lineWidth=3;c.beginPath();c.roundRect(-12,-24,24,48,6);c.fill();c.stroke();c.fillStyle='#2f505c';c.fillRect(-9,-13,18,9);c.fillRect(-9,9,18,7);c.fillStyle='#e0dca6';c.fillRect(-9,-23,5,3);c.fillRect(4,-23,5,3);c.restore();}else if(kind<4){c.fillStyle='#294e3d60';c.beginPath();c.ellipse(x+6,y+5,24,16,0,0,7);c.fill();c.fillStyle='#304d36';c.fillRect(x-3,y-16,6,19);for(let n=0;n<3;n++){c.fillStyle=['#2f6050','#387758','#4b8962'][n];c.beginPath();c.arc(x+(n-1)*8,y-17-n*4,17-n*2,0,7);c.fill();}}else if(kind===4){c.fillStyle='#2b4549';c.fillRect(x-2,y-27,4,30);c.fillStyle='#f2d58b';c.fillRect(x-5,y-30,10,6);}else if(kind===5){c.fillStyle='#2b4b4a';c.fillRect(x-12,y-8,24,16);c.fillStyle='#748e78';c.fillRect(x-13,y-10,26,4);}else if(kind===6){c.strokeStyle='#405857';c.lineWidth=3;c.beginPath();c.moveTo(x-20,y);c.lineTo(x+20,y);c.stroke();for(let k=-20;k<=20;k+=10)c.fillRect(x+k,y-5,2,10);}else if(kind===7){c.fillStyle='#749894';c.fillRect(x-18,y-9,36,18);c.strokeStyle='#274d4d';c.strokeRect(x-18,y-9,36,18);c.fillStyle='#d3be8e';c.fillRect(x-16,y-11,32,5);} }
 for(const f of list)if(f.kind==='metro'){const [x,y]=f.points[0];c.fillStyle='#284950';c.fillRect(x-18,y-14,36,28);c.fillStyle='#cbd9c6';c.fillRect(x-18,y-17,36,6);c.fillStyle='#f06065';c.font='bold 26px sans-serif';c.textAlign='center';c.fillText('М',x,y-23);}
 // Geographic names are drawn at real feature positions; repeated short road segments are suppressed.
 for(const f of list)if(f.name&&f.kind!=='building'&&f.kind!=='metro'&&f.points.length>2&&Math.hypot(f.maxX-f.minX,f.maxY-f.minY)>280){const a=f.points[Math.floor(f.points.length/2)];c.font='bold 13px sans-serif';c.textAlign='center';c.fillStyle='#e0e6d3';c.strokeStyle='#334d50';c.lineWidth=4;c.strokeText(f.name,a[0],a[1]-8);c.fillText(f.name,a[0],a[1]-8);}
 const u=this.data.university;c.font='bold 15px sans-serif';c.textAlign='center';c.fillStyle='#eedb9f';c.strokeStyle='#344e4c';c.lineWidth=4;c.strokeText('ФИНАНСОВЫЙ УНИВЕРСИТЕТ',u.x,u.y);c.fillText('ФИНАНСОВЫЙ УНИВЕРСИТЕТ',u.x,u.y);
 tex.refresh();const image=this.scene.add.image(ox,oy,key).setOrigin(0).setDepth(-100);this.chunks.set(key,image);}
 destroy(){for(const[key,img]of this.chunks){img.destroy();this.scene.textures.remove(key);}this.chunks.clear();}
}
