import { ProsyolokGame } from "./game.js";
import { MISSIONS, missionDistance, nearestMission, surfaceAt } from "./world.js";
import { SURFACES } from "./physics.js";
import { clearSave, loadGame, saveGame } from "./storage.js";

const $=(selector)=>document.querySelector(selector);
const $$=(selector)=>[...document.querySelectorAll(selector)];
let game=null,saveTimer=null,audio=null;
const toast=(message)=>{const element=$("#toast");element.textContent=message;element.classList.add("show");clearTimeout(element.timer);element.timer=setTimeout(()=>element.classList.remove("show"),1800);};

function initAudio(){if(audio)return;try{const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return;const context=new AudioContextClass();const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type="sawtooth";gain.gain.value=.0001;oscillator.connect(gain).connect(context.destination);oscillator.start();audio={context,oscillator,gain};}catch{/* Audio is optional. */}}
function updateAudio(){if(!audio||!game)return;const active=game.vehicle.engineOn&&!game.paused;audio.oscillator.frequency.setTargetAtTime(36+game.vehicle.rpm*.025,audio.context.currentTime,.06);audio.gain.gain.setTargetAtTime(active ? .018 : .0001,audio.context.currentTime,.08);}

function renderHud(){if(!game)return;const v=game.vehicle,surface=SURFACES[surfaceAt(v.x,v.z,game.weather)],mission=game.activeMission;$("#speed").textContent=Math.round(Math.abs(v.speed)*3.6);$("#gear").textContent=v.gear;$("#rpm").style.setProperty("--rpm",`${Math.min(100,v.rpm/62)}%`);$("#fuelValue").textContent=`${v.fuel.toFixed(1)} л`;$("#fuelBar").style.width=`${Math.min(100,v.fuel/45*100)}%`;$("#damageValue").textContent=`${Math.round(v.damage)}%`;$("#surfaceName").textContent=surface.name;$("#moneyValue").textContent=`${Math.round(v.money)} ₽`;$("#fpsValue").textContent=`${game.fps} FPS`;$("#engineButton").classList.toggle("active",v.engineOn);$("#lightButton").classList.toggle("active",v.headlights);$("#gearButton").textContent=v.gear;$("#missionTitle").textContent=mission?.title??"Свободная поездка";$("#missionDistance").textContent=mission?`${Math.round(missionDistance(mission,v.x,v.z,true))} м`:nearestMission(game.snapshot,v.x,v.z)?"Задание рядом":"Исследуйте деревню";$("#acceptMissionButton").hidden=Boolean(mission)||!nearestMission(game.snapshot,v.x,v.z);$("#cockpit").hidden=game.cameraMode!==1;updateAudio();}

async function launch(saved=null){$("#startScreen").hidden=true;$("#gameScreen").hidden=false;initAudio();game=new ProsyolokGame($("#gameCanvas"),saved??{});game.onMessage=toast;game.onUpdate=()=>{renderHud();clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveGame(game.snapshot).catch(()=>{}),1800);};game.onMissionComplete=(mission)=>{toast(`Задание выполнено: +${mission.reward} ₽`);navigator.vibrate?.([40,30,70]);saveGame(game.snapshot);};game.start();bindGameControls();renderHud();}
function bindHold(selector,key,value=1){const element=$(selector);const start=(event)=>{event.preventDefault();element.setPointerCapture?.(event.pointerId);game.input[key]=value;element.classList.add("pressed");};const end=(event)=>{event.preventDefault();game.input[key]=0;element.classList.remove("pressed");};element.onpointerdown=start;element.onpointerup=end;element.onpointercancel=end;element.onlostpointercapture=end;}

function bindGameControls(){
  bindHold("#gasButton","throttle");bindHold("#brakeButton","brake");bindHold("#handbrakeButton","handbrake");bindHold("#leftButton","steer",-1);bindHold("#rightButton","steer",1);
  const wheel=$("#steeringWheel");let wheelPointer=null;const move=(event)=>{if(event.pointerId!==wheelPointer)return;const box=wheel.getBoundingClientRect(),cx=box.left+box.width/2,cy=box.top+box.height/2,angle=Math.atan2(event.clientY-cy,event.clientX-cx)+Math.PI/2;game.input.steer=Math.max(-1,Math.min(1,angle/(Math.PI*.55)));wheel.style.transform=`rotate(${game.input.steer*105}deg)`;};wheel.onpointerdown=(event)=>{event.preventDefault();wheelPointer=event.pointerId;wheel.setPointerCapture(event.pointerId);move(event);};wheel.onpointermove=move;const release=()=>{wheelPointer=null;game.input.steer=0;wheel.style.transform="rotate(0deg)";};wheel.onpointerup=release;wheel.onpointercancel=release;
  $("#engineButton").onclick=()=>game.toggleEngine();$("#gearButton").onclick=()=>game.toggleGear();$("#cameraButton").onclick=()=>game.cycleCamera();$("#lightButton").onclick=()=>game.toggleLights();$("#hornButton").onclick=()=>{toast("Сигнал");navigator.vibrate?.(20);};$("#acceptMissionButton").onclick=()=>game.acceptNearbyMission();$("#pauseButton").onclick=()=>openMenu();
  window.onkeydown=(event)=>{if(!game)return;if(["ArrowUp","KeyW"].includes(event.code))game.input.throttle=1;if(["ArrowDown","KeyS"].includes(event.code))game.input.brake=1;if(["ArrowLeft","KeyA"].includes(event.code))game.input.steer=-1;if(["ArrowRight","KeyD"].includes(event.code))game.input.steer=1;if(event.code==="Space")game.input.handbrake=1;if(event.code==="KeyE"&&!event.repeat)game.toggleEngine();if(event.code==="KeyF"&&!event.repeat)game.cycleCamera();};window.onkeyup=(event)=>{if(["ArrowUp","KeyW"].includes(event.code))game.input.throttle=0;if(["ArrowDown","KeyS"].includes(event.code))game.input.brake=0;if(["ArrowLeft","ArrowRight","KeyA","KeyD"].includes(event.code))game.input.steer=0;if(event.code==="Space")game.input.handbrake=0;};
}

function openMenu(){game.paused=true;$("#menuDialog").showModal();renderMissionList();renderGarage();}
function closeMenu(){game.paused=false;$("#menuDialog").close();}
function renderMissionList(){$("#missionList").innerHTML=MISSIONS.map((m)=>`<article class="mission-card ${game.completedMissions.includes(m.id)?"done":""}"><span>${game.completedMissions.includes(m.id)?"Выполнено":game.activeMissionId===m.id?"В пути":`${m.reward} ₽`}</span><strong>${m.title}</strong><p>${m.text}</p></article>`).join("");}
function renderGarage(){const v=game.vehicle;$("#garageStats").innerHTML=`<span>Топливо <b>${v.fuel.toFixed(1)} л</b></span><span>Повреждения <b>${Math.round(v.damage)}%</b></span><span>Казна <b>${Math.round(v.money)} ₽</b></span>`;}

$("#newGameButton").onclick=async()=>{await clearSave();launch();};$("#continueButton").onclick=async()=>{const saved=await loadGame();if(saved)launch(saved);else toast("Сохранение не найдено");};$("#resumeButton").onclick=closeMenu;$("#saveButton").onclick=async()=>{await saveGame(game.snapshot);toast("Поездка сохранена");};$("#recoverButton").onclick=()=>{game.recover();closeMenu();};
$$('[data-service]').forEach((button)=>button.onclick=()=>{game.service(button.dataset.service);renderGarage();});$("#qualitySelect").onchange=(event)=>{game.quality=Number(event.target.value);};$("#controlsSelect").onchange=(event)=>{$("#wheelControl").hidden=event.target.value!=="wheel";$("#buttonControl").hidden=event.target.value!=="buttons";};$("#menuDialog").addEventListener("cancel",(event)=>{event.preventDefault();closeMenu();});document.addEventListener("visibilitychange",()=>{if(game){game.paused=document.hidden;if(document.hidden)saveGame(game.snapshot);}});
loadGame().then((saved)=>{$("#continueButton").hidden=!saved;$("#loadingScreen").classList.add("done");setTimeout(()=>$("#loadingScreen").remove(),350);});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
