import { CAPITAL_PROVINCES, MAP_SEAS, REGIONS } from "./regions.js";

export const CAMPAIGN_START_YEAR = 1095;

export const UNIT_TYPES = Object.freeze({
  levy: {
    id: "levy",
    name: "Ополчение",
    short: "Ополч.",
    icon: "♟",
    soldiers: 140,
    power: 1,
    cost: 120,
    foodCost: 12,
    upkeep: 18,
    requirement: null,
  },
  archers: {
    id: "archers",
    name: "Лучники",
    short: "Луки",
    icon: "➶",
    soldiers: 100,
    power: 1.45,
    cost: 210,
    foodCost: 10,
    upkeep: 27,
    requirement: "barracks",
  },
  knights: {
    id: "knights",
    name: "Рыцари",
    short: "Рыцари",
    icon: "♞",
    soldiers: 60,
    power: 2.8,
    cost: 390,
    foodCost: 18,
    upkeep: 52,
    requirement: "castle",
  },
});

export const BUILDING_TYPES = Object.freeze({
  farm: {
    id: "farm",
    name: "Поля",
    icon: "♨",
    description: "+24 еды за ход",
    baseCost: 240,
    authorityCost: 0,
  },
  market: {
    id: "market",
    name: "Рынок",
    icon: "⚖",
    description: "+70 золота за ход",
    baseCost: 320,
    authorityCost: 0,
  },
  barracks: {
    id: "barracks",
    name: "Казармы",
    icon: "⚔",
    description: "Открывает лучников",
    baseCost: 410,
    authorityCost: 4,
  },
  castle: {
    id: "castle",
    name: "Замок",
    icon: "♜",
    description: "+30% к защите, открывает рыцарей",
    baseCost: 620,
    authorityCost: 8,
  },
});

export const FACTIONS = Object.freeze({
  england: {
    id: "england",
    name: "Королевство Англия",
    shortName: "Англия",
    ruler: "Вильгельм II Рыжий",
    color: "#b93f4b",
    darkColor: "#6d2630",
    accent: "#f1d28a",
    emblem: "♜",
    capital: CAPITAL_PROVINCES.england,
    trait: "Королевская казна",
    bonus: "+12% дохода с рынков",
    marketBonus: 1.12,
    farmBonus: 1,
    recruitBonus: 1,
    powerBonus: 1,
    defenseBonus: 1,
    description: "Богатый островной престол с сильными рыцарями и удобным началом кампании.",
    difficulty: "Легко",
    playable: true,
  },
  france: {
    id: "france",
    name: "Королевство Франция",
    shortName: "Франция",
    ruler: "Филипп I",
    color: "#3159a7",
    darkColor: "#1d3567",
    accent: "#e8c86b",
    emblem: "⚜",
    capital: CAPITAL_PROVINCES.france,
    trait: "Знамя лилий",
    bonus: "+10% силы ополчения",
    marketBonus: 1,
    farmBonus: 1,
    recruitBonus: 1,
    powerBonus: 1.1,
    defenseBonus: 1,
    description: "Сердце Западной Европы. Много земель, доходов и опасных границ.",
    difficulty: "Средне",
    playable: true,
  },
  hre: {
    id: "hre",
    name: "Священная Римская империя",
    shortName: "Империя",
    ruler: "Генрих IV",
    color: "#c6a03b",
    darkColor: "#745d20",
    accent: "#171a1c",
    emblem: "♛",
    capital: CAPITAL_PROVINCES.hre,
    trait: "Имперские города",
    bonus: "+1 авторитет за три провинции",
    marketBonus: 1,
    farmBonus: 1,
    recruitBonus: 1,
    powerBonus: 1,
    defenseBonus: 1,
    description: "Обширные владения в центре континента. Сильная экономика, но враги повсюду.",
    difficulty: "Сложно",
    playable: true,
  },
  castile: {
    id: "castile",
    name: "Королевство Кастилия",
    shortName: "Кастилия",
    ruler: "Альфонсо VI",
    color: "#8d345e",
    darkColor: "#51203a",
    accent: "#f3d7a2",
    emblem: "♜",
    capital: CAPITAL_PROVINCES.castile,
    trait: "Земли Реконкисты",
    bonus: "+18% еды с полей",
    marketBonus: 1,
    farmBonus: 1.18,
    recruitBonus: 1,
    powerBonus: 1,
    defenseBonus: 1,
    description: "Растущее королевство Иберии. Развивайте плодородные земли и завершите Реконкисту.",
    difficulty: "Легко",
    playable: true,
  },
  denmark: {
    id: "denmark",
    name: "Королевство Дания",
    shortName: "Дания",
    ruler: "Эрик I Добрый",
    color: "#c95646",
    darkColor: "#743026",
    accent: "#f3eee3",
    emblem: "✣",
    capital: CAPITAL_PROVINCES.denmark,
    trait: "Морские дружины",
    bonus: "На 12% дешевле набор войск",
    marketBonus: 1,
    farmBonus: 1,
    recruitBonus: 0.88,
    powerBonus: 1,
    defenseBonus: 1,
    description: "Компактное северное королевство с дешёвыми дружинами и выходом к морям.",
    difficulty: "Средне",
    playable: true,
  },
  poland: {
    id: "poland",
    name: "Королевство Польша",
    shortName: "Польша",
    ruler: "Владислав Герман",
    color: "#d8d5cf",
    darkColor: "#8c2836",
    accent: "#9e2f40",
    emblem: "♞",
    capital: CAPITAL_PROVINCES.poland,
    trait: "Пограничные крепости",
    bonus: "+12% к защите своих земель",
    marketBonus: 1,
    farmBonus: 1,
    recruitBonus: 1,
    powerBonus: 1,
    defenseBonus: 1.12,
    description: "Крепкое восточное королевство. Удерживайте рубежи и расширяйтесь к Балтике.",
    difficulty: "Средне",
    playable: true,
  },
  byzantium: {
    id: "byzantium",
    name: "Византийская империя",
    shortName: "Византия",
    ruler: "Алексей I Комнин",
    color: "#8c4ba7",
    darkColor: "#4d275e",
    accent: "#e7c668",
    emblem: "☩",
    capital: CAPITAL_PROVINCES.byzantium,
    trait: "Ромейская выучка",
    bonus: "+8% силы всех войск",
    marketBonus: 1,
    farmBonus: 1,
    recruitBonus: 1,
    powerBonus: 1.08,
    defenseBonus: 1,
    description: "Богатая наследница Рима в окружении врагов. Мощная армия требует умелого правителя.",
    difficulty: "Сложно",
    playable: true,
  },
  venice: {
    id: "venice",
    name: "Венецианская республика",
    shortName: "Венеция",
    ruler: "Дож Витале Фальер",
    color: "#3e9b92",
    darkColor: "#215d58",
    accent: "#efd181",
    emblem: "☼",
    capital: CAPITAL_PROVINCES.venice,
    trait: "Лагунная торговля",
    bonus: "+25% дохода с рынков",
    marketBonus: 1.25,
    farmBonus: 1,
    recruitBonus: 1,
    powerBonus: 1,
    defenseBonus: 1,
    description: "Небольшая, но очень богатая республика. Покупайте влияние и выбирайте войны осторожно.",
    difficulty: "Сложно",
    playable: true,
  },
  scotland: {
    id: "scotland", name: "Королевство Шотландия", shortName: "Шотландия", ruler: "Дональд III",
    color: "#4e7690", darkColor: "#294456", accent: "#d9e4dd", emblem: "✦", capital: CAPITAL_PROVINCES.scotland,
    trait: "Горцы", bonus: "Стойкие ополченцы", marketBonus: 1, farmBonus: 1, recruitBonus: 1.06, defenseBonus: 1.04,
    description: "", difficulty: "", playable: false,
  },
  leon: {
    id: "leon", name: "Королевство Леон", shortName: "Леон", ruler: "Уррака",
    color: "#71529a", darkColor: "#41305a", accent: "#dfcbea", emblem: "✥", capital: CAPITAL_PROVINCES.leon,
    trait: "", bonus: "", marketBonus: 1, farmBonus: 1.05, recruitBonus: 1, defenseBonus: 1,
    description: "", difficulty: "", playable: false,
  },
  aragon: {
    id: "aragon", name: "Королевство Арагон", shortName: "Арагон", ruler: "Педро I",
    color: "#d28e32", darkColor: "#774e19", accent: "#7d2630", emblem: "☷", capital: CAPITAL_PROVINCES.aragon,
    trait: "", bonus: "", marketBonus: 1.05, farmBonus: 1, recruitBonus: 1, defenseBonus: 1,
    description: "", difficulty: "", playable: false,
  },
  sicily: {
    id: "sicily", name: "Сицилийское графство", shortName: "Сицилия", ruler: "Рожер I",
    color: "#a88650", darkColor: "#5e4828", accent: "#f0dfb4", emblem: "✢", capital: CAPITAL_PROVINCES.sicily,
    trait: "", bonus: "", marketBonus: 1, farmBonus: 1.08, recruitBonus: 1, defenseBonus: 1,
    description: "", difficulty: "", playable: false,
  },
  hungary: {
    id: "hungary", name: "Королевство Венгрия", shortName: "Венгрия", ruler: "Кальман Книжник",
    color: "#4e8a68", darkColor: "#28503a", accent: "#e5d6a4", emblem: "✤", capital: CAPITAL_PROVINCES.hungary,
    trait: "", bonus: "", marketBonus: 1, farmBonus: 1.08, recruitBonus: 1, defenseBonus: 1,
    description: "", difficulty: "", playable: false,
  },
  papacy: {
    id: "papacy", name: "Папская область", shortName: "Рим", ruler: "Урбан II",
    color: "#e3d9bb", darkColor: "#8e8267", accent: "#b89a3f", emblem: "☧", capital: CAPITAL_PROVINCES.papacy,
    trait: "", bonus: "", marketBonus: 1.1, farmBonus: 1, recruitBonus: 1, defenseBonus: 1.08,
    description: "", difficulty: "", playable: false,
  },
  rebels: {
    id: "rebels", name: "Независимые владения", shortName: "Вольные земли", ruler: "Местная знать",
    color: "#77766f", darkColor: "#474741", accent: "#d8d1bd", emblem: "◆", capital: null,
    trait: "", bonus: "", marketBonus: 1, farmBonus: 1, recruitBonus: 1, defenseBonus: 1,
    description: "", difficulty: "", playable: false,
  },
});

export const PROVINCES = REGIONS;

export const TERRAIN = Object.freeze({
  plains: { name: "Равнины", defense: 1, icon: "≈" },
  forest: { name: "Леса", defense: 1.12, icon: "♠" },
  hills: { name: "Холмы", defense: 1.18, icon: "▲" },
});

export const SEAS = MAP_SEAS;

export const STARTING_RELATIONS = Object.freeze({
  england: { france: "war", scotland: "war" },
  france: { england: "war", hre: "war" },
  hre: { france: "war", venice: "neutral", poland: "neutral", hungary: "neutral" },
  castile: { leon: "neutral", aragon: "neutral", rebels: "war" },
  denmark: { rebels: "war", hre: "neutral" },
  poland: { rebels: "war", hre: "neutral", hungary: "neutral" },
  byzantium: { rebels: "war", hungary: "neutral", sicily: "war" },
  venice: { hre: "neutral", hungary: "neutral", byzantium: "neutral" },
});

export const RANDOM_EVENTS = Object.freeze([
  { title: "Добрый урожай", text: "Амбары полны, а на рынках падают цены на зерно.", food: 90, gold: 0, authority: 0 },
  { title: "Ярмарочный сезон", text: "Купцы со всего континента прибыли в ваши города.", food: 0, gold: 180, authority: 0 },
  { title: "Спор баронов", text: "Знатные дома требуют от короны новых привилегий.", food: 0, gold: 0, authority: -8 },
  { title: "Верность вассалов", text: "Ваши победы укрепили уважение к престолу.", food: 0, gold: 0, authority: 10 },
  { title: "Суровая зима", text: "Холода погубили часть запасов.", food: -70, gold: 0, authority: 0 },
]);

export const PLAYABLE_FACTIONS = Object.values(FACTIONS).filter((faction) => faction.playable);
